version: '3.7'

services:
  signature-service:
    container_name: sigs
    # image: maven:3.8.3-openjdk-11
    build: 
      context: ./
    networks:
      - signature-service-network
      - todo-app-network
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
      - 8080:8080
      - 5678:5678
      - 9229:9229
      - 9219:9219

  signature-couchbase-db:
    container_name: signature-couchbase-db
    image: couchbase
    networks:
      - signature-service-network
    volumes:
      - signature-couchbase-vol:/opt/couchbase/var
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"

networks:
  signature-service-network:
    name: signature-service-network
  todo-app-network:
    name: todo-app-network

volumes:
  signature-couchbase-vol:
    name: signature-couchbase-vol
