version: '3.7'

services:
  signature-service:
    container_name: sigs
    build: 
      context: ./Dockerfile
      dockerfile: ./Dockerfile
    networks:
      - signature-service-network
      - todo-app-network
    volumes:
      - ./app:/app
    environment:
      - INTERNAL_PORT=3000
      - EXTERNAL_PORT=3000
      - DEBUG_PORT=9229
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - signature-couchbase-db

  signature-couchbase-db:
    container_name: signature-couchbase-db
    image: couchbase
    networks:
      - signature-service-network
    volumes:
      - signature-couchbase-vol:/opt/couchbase/var
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"

networks:
  signature-service-network:
    name: signature-service-network
  todo-app-network:
    name: todo-app-network

volumes:
  signature-couchbase-vol:
    name: signature-couchbase-vol
